source "https://rubygems.org"

group :development do
  gem "vagrant", git: "https://github.com/mitchellh/vagrant.git"
end

group :plugins do
  gem "vagrant-berkshelf", path: "../"
  gem "vagrant-omnibus"
end
