# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.require_version ">= 1.5.0"

Vagrant.configure("2") do |config|
  config.vm.hostname = "vagrant-builder-int"
  config.vm.box      = "opscode-ubuntu-14.04"
  config.vm.box_url  = "https://vagrantcloud.com/chef/ubuntu-14.04/version/1/provider/virtualbox.box"

  config.vm.network :private_network, type: "dhcp"

  config.omnibus.chef_version = :latest

  config.vm.provision :chef_client do |chef|
    chef.chef_server_url     = "https://api.opscode.com/organizations/undeadlabs"
    chef.validation_key_path = File.expand_path("~/.chef/undeadlabs-validator.pem")
    chef.run_list            = ["apt::default"]
  end
end
